#!/usr/bin/env python3
"""Render mxGraphModel XML into a self-contained, editable .drawio.svg.

Runs the official diagrams.net viewer in headless Chrome and serializes
`graph.getSvg(...)` — the editor's own export path, so output matches
editor-made assets (preamble, switch/foreignObject text fallbacks, "Text is
not SVG" marker, quoted font-family attrs). The compressed source is
re-embedded in `<svg content="...">` and its roundtrip verified before exit.

The canvas exports theme-aware — `light-dark()` background under
`color-scheme: light dark` — so inlined diagrams follow the site theme
instead of the OS preference. `--background transparent` opts out.

Chromium is taken from PATH, else the Playwright cache, else installed via
npx. viewer.min.js is cached in the temp dir on first run.
"""

import argparse
import base64
import html
import json
import os
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.parse
import urllib.request
import zlib

VIEWER_URL = 'https://viewer.diagrams.net/js/viewer.min.js'
VIEWER_CACHE = pathlib.Path(tempfile.gettempdir()) / 'drawio-viewer.min.js'
CHROME_CANDIDATES = ('google-chrome', 'google-chrome-stable', 'chromium', 'chromium-browser',
                    'chrome')
# Playwright cache layout, per platform.
PLAYWRIGHT_BINARIES = (
    'chromium-*/chrome-win64/chrome.exe',
    'chromium-*/chrome-win/chrome.exe',
    'chromium-*/chrome-linux/chrome',
    'chromium-*/chrome-mac/Chromium.app/Contents/MacOS/Chromium',
    'chromium_headless_shell-*/chrome-headless-shell-win64/chrome-headless-shell.exe',
    'chromium_headless_shell-*/chrome-headless-shell-linux/chrome-headless-shell',
    'chromium_headless_shell-*/chrome-headless-shell-mac/chrome-headless-shell',
)
# viewer.diagrams.net rejects the urllib default agent.
VIEWER_UA = 'Mozilla/5.0'
PREAMBLE = ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<!-- Do not edit this file with editors other than draw.io -->\n'
            '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"'
            ' "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n')


def playwright_browsers_dir() -> pathlib.Path:
    override = os.environ.get('PLAYWRIGHT_BROWSERS_PATH')
    if override:
        return pathlib.Path(override)
    if sys.platform == 'win32':
        return pathlib.Path(os.environ['LOCALAPPDATA']) / 'ms-playwright'
    if sys.platform == 'darwin':
        return pathlib.Path.home() / 'Library' / 'Caches' / 'ms-playwright'
    return pathlib.Path.home() / '.cache' / 'ms-playwright'


def find_playwright_chromium() -> str | None:
    root = playwright_browsers_dir()
    if not root.is_dir():
        return None
    for pattern in PLAYWRIGHT_BINARIES:
        # Newest revision first (lexical sort — revisions are numeric).
        for path in sorted(root.glob(pattern), reverse=True):
            if path.is_file():
                return str(path)
    return None


def install_playwright_chromium() -> str | None:
    npx = shutil.which('npx')
    if not npx:
        return None
    print('no Chrome/Chromium found — installing Playwright chromium')
    subprocess.run([npx, '--yes', 'playwright', 'install', 'chromium'],
                   check=False, timeout=900)
    return find_playwright_chromium()


def find_chrome() -> str:
    for name in CHROME_CANDIDATES:
        path = shutil.which(name)
        if path:
            return path
    return (find_playwright_chromium()
            or install_playwright_chromium()
            or sys.exit('error: no Chrome/Chromium available — tried PATH '
                        f'({", ".join(CHROME_CANDIDATES)}), the Playwright browser cache '
                        f'({playwright_browsers_dir()}), and `npx playwright install chromium`'))


def ensure_viewer() -> pathlib.Path:
    if not VIEWER_CACHE.exists():
        print(f'fetching {VIEWER_URL} -> {VIEWER_CACHE}')
        request = urllib.request.Request(VIEWER_URL, headers={'User-Agent': VIEWER_UA})
        with urllib.request.urlopen(request) as response:
            VIEWER_CACHE.write_bytes(response.read())
    return VIEWER_CACHE


def build_mxfile(model_xml: str, diagram_id: str, compress: bool) -> str:
    if compress:
        encoded = urllib.parse.quote(model_xml, safe='')
        deflate = zlib.compressobj(9, zlib.DEFLATED, -15)
        payload = base64.b64encode(deflate.compress(encoded.encode()) + deflate.flush()).decode()
    else:
        payload = model_xml
    return (f'<mxfile host="app.diagrams.net">'
            f'<diagram id="{diagram_id}" name="Page-1">{payload}</diagram></mxfile>')


def render_svg(model_xml: str, diagram_id: str, border: int, background: str | None,
               chrome: str) -> str:
    config = json.dumps({
        'xml': build_mxfile(model_xml, diagram_id, compress=False),
        'scale': 1, 'border': 0, 'resize': True, 'nav': False, 'toolbar': None,
    })
    # A background makes the viewer emit the full-canvas <rect> and the
    # light-dark() root style; the 12th argument is its color-scheme value.
    bg = json.dumps(background)
    scheme = json.dumps('light dark' if background else None)
    page = f"""<!doctype html><html><head><meta charset="utf-8"></head><body>
<div id="diagram" data-mxgraph='{html.escape(config, quote=True)}'></div>
<script src="file://{ensure_viewer()}"></script>
<script>
window.addEventListener('load', function() {{
  var out = document.createElement('pre'); out.id = 'serialized-out';
  try {{
    GraphViewer.createViewerForElement(document.getElementById('diagram'), function(viewer) {{
      var svg = viewer.graph.getSvg({bg}, 1, {border}, null, null, null, null,
        null, null, null, null, {scheme});
      out.textContent = new XMLSerializer().serializeToString(svg);
      document.body.appendChild(out);
    }});
  }} catch (e) {{ out.textContent = 'ERR ' + e.message; document.body.appendChild(out); }}
}});
</script>
</body></html>"""

    with tempfile.TemporaryDirectory() as tmp:
        harness = pathlib.Path(tmp) / 'export.html'
        harness.write_text(page, encoding='utf-8')
        result = subprocess.run(
            [chrome, '--headless=new', '--disable-gpu', '--no-sandbox',
             '--virtual-time-budget=20000', '--dump-dom', f'file://{harness}'],
            capture_output=True, text=True, timeout=120,
        )
    m = re.search(r'<pre id="serialized-out">(.*?)</pre>', result.stdout, re.S)
    if not m:
        sys.exit('error: viewer produced no output — is viewer.min.js intact and Chrome working?')
    svg = html.unescape(m.group(1))
    if svg.startswith('ERR') or not svg.startswith('<svg'):
        sys.exit(f'error: viewer failed: {svg[:200]}')
    return svg


def verify_roundtrip(svg_path: pathlib.Path, model_xml: str) -> int:
    text = svg_path.read_text(encoding='utf-8')
    mxfile = html.unescape(re.search(r'content="([^"]*)"', text).group(1))
    payload = re.search(r'<diagram[^>]*>([^<]+)</diagram>', mxfile).group(1)
    decoded = urllib.parse.unquote(zlib.decompress(base64.b64decode(payload), -15).decode())
    cells = len(re.findall(r'<mxCell', decoded))
    if decoded != model_xml:
        sys.exit('error: roundtrip mismatch — embedded source does not decode back to the input XML')
    return cells


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('xml', help='mxGraphModel XML file (root element <mxGraphModel>)')
    parser.add_argument('out', help='output .drawio.svg path')
    parser.add_argument('--border', type=int, default=40,
                        help='canvas padding in px (default 40, matches existing assets)')
    parser.add_argument('--background', default='#ffffff',
                        help="canvas color, exported as light-dark(color, #121212); "
                             "'transparent' omits canvas and color-scheme")
    parser.add_argument('--screenshot', metavar='PNG',
                        help='also screenshot the finished file for visual verification')
    args = parser.parse_args()

    model_xml = pathlib.Path(args.xml).read_text(encoding='utf-8').strip()
    if not model_xml.startswith('<mxGraphModel'):
        sys.exit('error: input must be bare mxGraphModel XML (use decode_drawio_svg.py to obtain it)')

    out = pathlib.Path(args.out)
    diagram_id = out.name.removesuffix('.drawio.svg').removesuffix('.svg')
    chrome = find_chrome()

    background = None if args.background == 'transparent' else args.background
    svg = render_svg(model_xml, diagram_id, args.border, background, chrome)
    content_attr = html.escape(build_mxfile(model_xml, diagram_id, compress=True), quote=True)
    # Last root attribute, as drawio writes it. Callable replacement so the
    # base64 payload is never read as a backreference.
    svg = re.sub(r'^(<svg\b[^>]*?)>',
                 lambda m: f'{m.group(1)} content="{content_attr}">', svg, count=1)

    out.parent.mkdir(parents=True, exist_ok=True)
    # LF explicitly — the asset must not differ by the exporting platform.
    out.write_text(PREAMBLE + svg, encoding='utf-8', newline='\n')
    cells = verify_roundtrip(out, model_xml)
    print(f'{out}: {out.stat().st_size} bytes, {cells} cells, roundtrip ok')

    if args.screenshot:
        subprocess.run(
            [chrome, '--headless=new', '--disable-gpu', '--no-sandbox', '--hide-scrollbars',
             '--window-size=1800,1200', '--virtual-time-budget=8000',
             f'--screenshot={args.screenshot}', f'file://{out.resolve()}'],
            capture_output=True, timeout=120,
        )
        print(f'screenshot: {args.screenshot}')


if __name__ == '__main__':
    main()
